apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: service-phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: phpmyadmin-config
          mountPath: /var/www/localhost/htdocs/config.inc.php
          subPath: config.inc.php
        - name: phpmyadmin-persistent-storage
          mountPath: /var/www/localhost/htdocs
        livenessProbe:
          httpGet:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: phpmyadmin-config
        configMap:
           name: phpmyadmin-config
      - name: phpmyadmin-persistent-storage
        persistentVolumeClaim:
          claimName: phpmyadmin-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  ports:
  - name: phpmyadmin
    protocol: TCP
    port: 5000
    targetPort: 80
  selector:
    app: phpmyadmin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-config
data:
  config.inc.php: |
    <?php
    $i = 0;
    $i++;
    $cfg['Servers'][$i]['host'] = 'mysql';
    $cfg['blowfish_secret'] = 'i0ULtq/xlL:x;F7AjIYH=2I82cI[Vrly';
    $cfg['DefaultLang'] = 'en';
    $cfg['ServerDefault'] = 1;
    $cfg['UploadDir'] = '';
    $cfg['SaveDir'] = '';
    $cfg['PmaAbsoluteUri'] = '/phpmyadmin/';
    $cfg['LoginCookieValidity'] = 2000;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpmyadmin-pv-claim
  labels:
    app: phpmyadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi


# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     metallb.universe.tf/allow-shared-ip: shared
#   name: phpmyadmin
#   labels:
#     app: phpmyadmin
# spec:
#   selector:
#     app: phpmyadmin
#   type: LoadBalancer
#   ports:
#     - port: 5000
#       name: phpmyadmin
#       targetPort: 5000
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: phpmyadmin
#   labels:
#     app: phpmyadmin
# spec:
#   selector:
#     matchLabels:
#       app: phpmyadmin
#   replicas: 1
#   template:
#     metadata:
#       name: phpmyadmin
#       labels:
#         app: phpmyadmin
#     spec:
#       containers:
#         - name: phpmyadmin
#           image: service-phpmyadmin
#           imagePullPolicy: Never
#           ports:
#             - containerPort: 5000
#           volumeMounts:
#             - name: phpmyadmin-config
#               subPath: config.inc.php
#               mountPath: /www/config.inc.php
#               readOnly: true
#       volumes:
#         - name: phpmyadmin-config
#           configMap:
#             name: phpmyadmin-config
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: phpmyadmin-config
#   labels:
#     app: phpmyadmin
# data:
#   config.inc.php: |
#     <?php
#     /**
#      * phpMyAdmin sample configuration, you can use it as base for
#      * manual configuration. For easier setup you can use setup/
#      *
#      * All directives are explained in documentation in the doc/ folder
#      * or at <https://docs.phpmyadmin.net/>.
#      *
#     * @package PhpMyAdmin
#      */

#     /**
#      * This is needed for cookie based authentication to encrypt password in
#      * cookie. Needs to be 32 chars long.
#      */
#     $cfg['blowfish_secret'] = '01234567890123456789012345678912'; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */

#     /**
#      * Servers configuration
#      */
#     $i = 0;

#     /**
#      * First server
#      */
#     $i++;

#     /* Authentication type */
#     $cfg['Servers'][$i]['auth_type'] = 'cookie';

#     /* Server parameters */
#     $cfg['Servers'][$i]['host'] = 'mysql';
#     $cfg['Servers'][$i]['port'] = '3306';
#     $cfg['Servers'][$i]['user'] = 'admin';
#     $cfg['Servers'][$i]['password'] = 'password';
#     $cfg['Servers'][$i]['compress'] = 'false';
#     $cfg['Servers'][$i]['AllowNoPassword'] = 'true';

#     /**
#      * Directories for saving/loading files from server
#      */
#     $cfg['UploadDir'] = '';
#     $cfg['SaveDir'] = '';
#     $cfg['PmaAbsoluteUri'] = '/phpmyadmin/';
