apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: service-wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: password
        volumeMounts:
        - name: wp-config
          mountPath: /var/www/localhost/htdocs/wp-config.php
          subPath: wp-config.php
        - name: wordpress-persistent-storage
          mountPath: /var/www/localhost/htdocs
        livenessProbe:
          httpGet:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: wp-config
        configMap:
          name: wordpress-config
          items:
          - key: wp-config.php
            path: wp-config.php
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: ClusterIP
  ports:
  - name: wordpress
    port: 5050
    targetPort: 80
  selector:
    app: wordpress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  wp-config.php: |
    <?php
    define( 'WP_SITEURL',       '/wordpress/'  );
    define( 'WP_HOME',          '/wordpress/'  );
    define( 'DB_NAME',          'wordpress'  );
    define( 'DB_USER',          'root');        # DB_USER와 DB_PASSWORD는 DB_HOST의 user, passwd
    define( 'DB_PASSWORD',      'root');
    define( 'DB_HOST',          'mysql'  );
    define( 'DB_CHARSET',       'utf8mb4'  );
    define( 'DB_COLLATE',       '' );
    define( 'AUTH_KEY',         '|WnO`(KpO0}T|&YE/6M6:jD]:i7^mU> q>8m|]uzQ|_ZWNG`=Nx%5$~ pxQ{Zf.]');
    define( 'SECURE_AUTH_KEY',  'Lq<{-3 VVvz1V($7=V~;lZjE4I;uO-N_$Bu-C`R>GR2N&uTRh4+q{k*Hb?tBfqk(');
    define( 'LOGGED_IN_KEY',    'HvqcUkrz-AAC|2j*al!&yurK|^t}As/_Q6`qYRviP8++=QnMzF!|=1r8E;+JB~^e');
    define( 'NONCE_KEY',        '}*<wOAI__t`=tfR9&+X}Npg+_=0jiM`klyXDGa)rp~iFw-jWwKh$$I[*h=u,pVwn');
    define( 'AUTH_SALT',        'H<|TB.}.1;!uFen&z&/8/vAt>$~R bkQu$DW{u}@-A;u13Hk%J~]g+PtOT2+>HhH');
    define( 'SECURE_AUTH_SALT', '+z~LPwq)r;q01%w6w6Y4O^wm*$WC4sF.hT|tH, dWB(l%<:}$zFjX]R-DY<.|3>$');
    define( 'LOGGED_IN_SALT',   'k)0t0 DiV|=mOUw)1Je76zpZ9]/?|66t3`*|]H3+?V&h(ZJ~pz-`LL-AKy~jGNjz');
    define( 'NONCE_SALT',       '?!V/n-AJW}=bT|L.i7/yh5W}Gg?x~hR:JSKLv@vX8:fIa`;mC&~#wHU8flh%8}Z^');
    $table_prefix = 'wp_';
    define( 'WP_DEBUG', false  );
    if ( ! defined( 'ABSPATH'  )  ) {
      define( 'ABSPATH', __DIR__ . '/'  );
    }
    require_once ABSPATH . 'wp-settings.php';
    if ( ! empty( $_SERVER['HTTP_X_FORWARDED_HOST']  )  ) {
      $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
stringData:
  username: juhlee
  password: juhlee


# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     metallb.universe.tf/allow-shared-ip: shared
#   name: wordpress
#   labels:
#     app: wordpress
# spec:
#   selector:
#     app: wordpress
#   type: LoadBalancer
#   ports:
#     - port: 5050
#       name: wordpress
#       targetPort: 5050
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wordpress
#   labels:
#     app: wordpress
# spec:
#   selector:
#     matchLabels:
#       app: wordpress
#   replicas: 1
#   template:
#     metadata:
#       name: wordpress
#       labels:
#         app: wordpress
#     spec:
#       containers:
#         - name: wordpress
#           image: service-wordpress
#           imagePullPolicy: Never
#           ports:
#             - containerPort: 5050
#           volumeMounts:
#             - name: wordpress-config
#               subPath: wp-config.php
#               mountPath: /www/wordpress/wp-config.php
#               readOnly: true
#       volumes:
#         - name: wordpress-config
#           configMap:
#             name: wordpress-config
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: wordpress-config
#   labels:
#     app: wordpress
# data:
#   wp-config.php:  |
#     <?php
#     /**
#     * The base configuration for WordPress
#     *
#     * The wp-config.php creation script uses this file during the
#     * installation. You don't have to use the web site, you can
#     * copy this file to "wp-config.php" and fill in the values.
#     *
#     * This file contains the following configurations:
#     *
#     * * MySQL settings
#     * * Secret keys
#     * * Database table prefix
#     * * ABSPATH
#     *
#     * @link https://codex.wordpress.org/Editing_wp-config.php
#     *
#     * @package WordPress
#     */

#     define( 'WP_SITEURL',       'http://nginx:5050/'  );
#     define( 'WP_HOME',          'http://nginx:5050/'  );

#     // ** MySQL settings - You can get this info from your web host ** //
#     /** The name of the database for WordPress */
#     define( 'DB_NAME', 'wordpress' );

#     /** MySQL database username */
#     define( 'DB_USER', 'admin' );

#     /** MySQL database password */
#     define( 'DB_PASSWORD', 'password' );

#     /** MySQL hostname */
#     define( 'DB_HOST', 'mysql' );


#     /** Database Charset to use in creating database tables. */
#     define( 'DB_CHARSET', 'utf8' );

#     /** The Database Collate type. Don't change this if in doubt. */
#     define( 'DB_COLLATE', '' );

#     /**#@+
#     * Authentication Unique Keys and Salts.
#     *
#     * Change these to different unique phrases!
#     * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
#     * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
#     *
#     * @since 2.6.0
#     */
#     define( 'AUTH_KEY',         'put your unique phrase here' );
#     define( 'SECURE_AUTH_KEY',  'put your unique phrase here' );
#     define( 'LOGGED_IN_KEY',    'put your unique phrase here' );
#     define( 'NONCE_KEY',        'put your unique phrase here' );
#     define( 'AUTH_SALT',        'put your unique phrase here' );
#     define( 'SECURE_AUTH_SALT', 'put your unique phrase here' );
#     define( 'LOGGED_IN_SALT',   'put your unique phrase here' );
#     define( 'NONCE_SALT',       'put your unique phrase here' );

#     /**#@-*/

#     /**
#     * WordPress Database Table prefix.
#     *
#     * You can have multiple installations in one database if you give each
#     * a unique prefix. Only numbers, letters, and underscores please!
#     */
#     $table_prefix = 'wp_';

#     /**
#     * For developers: WordPress debugging mode.
#     *
#     * Change this to true to enable the display of notices during development.
#     * It is strongly recommended that plugin and theme developers use WP_DEBUG
#     * in their development environments.
#     *
#     * For information on other constants that can be used for debugging,
#     * visit the Codex.
#     *
#     * @link https://codex.wordpress.org/Debugging_in_WordPress
#     */
#     define( 'WP_DEBUG', false );

#     /* That's all, stop editing! Happy publishing. */

#     /** Absolute path to the WordPress directory. */
#     if ( ! defined( 'ABSPATH' ) ) {
#       define( 'ABSPATH', dirname( __FILE__ ) . '/' );
#     }

#     /** Sets up WordPress vars and included files. */
#     require_once( ABSPATH . 'wp-settings.php' );
